version: '3.8'

services:
  db:
    image: postgres:15
    container_name: flight-booking-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: newpassword999
      POSTGRES_DB: flight_booking_db
    ports:
      - "5444:5432"
    volumes:
      - pg_data_flight_new:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d flight_booking_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pg_data_flight_new: